### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by nvdk**
the recent update of this addon left the readme somewhat outdated, I've tried to make it more inline with what's now required.

### CODE REVIEW

**Comment by nvdk** [comment]
should we also say something about logout?

**Comment by nvdk** [comment]
ah just noticed that sam already update the readme in his PR, will resolve the conflicts :)

**Comment by Windvis** [comment]
Yea, writing docs isn't my strongest skill so feel free to improve it further :smile: . I was thinking of adding an API docs section where the properties of the yielded objects are explained. That's probably better than simply linking to the dummy app version. Haven't had the time to do that yet though.

**Comment by nvdk** [comment]
I think you already did a better effort than me, so I've just closed this for now :+1:

**Pull request closed without merging**
