### PR TITLE
modernize package and drop torii dependency

### PR DESCRIPTION
**Pull request by nvdk**
initial go at a modern acmidm-login package. Also went for addon v2 package format, so a lot of things are still broken at the moment:

- [x] figure out a release-it config or replacement for monorepo's
- [x] drone pipeline needs to be set up for v2 addon
- [x] document session invalidation
- [ ] add example error handling in docs
- [x] add example for acm idm switch in docs

### CODE REVIEW

**Comment by ValenberghsSven** [comment]
@nvdk Any progress on this? Depending on this PR to upgrade to ember v4.4 (outdated torii@0.10.1)

**Comment by nvdk** [comment]
If you don't need the switch functionality this is probably good to go. Feel free to test with 2.0.0-beta.1 and report back here :)

**Comment by Windvis** [comment]
I've integrated the v2 update in loket which also uses the switch functionality and some error handling (not sure if everything is covered).

https://github.com/lblod/frontend-loket/pull/282

**Comment by nvdk** [comment]
thanks for the ping @Windvis, will try to have a look later this week and update the PR with documentation for switch based on your example

**Pull request merged**
